version: "3"
 
services:
   wordpress-db:
     container_name: wordpress-db
     image: mysql:latest
     volumes:
       - /srv/docker/wordpress/db:/var/lib/mysql
     restart: always
     environment:
       MYSQL_DATABASE: wordpress
       MYSQL_USER: cloud1
       MYSQL_PASSWORD: cloud1
       MYSQL_RANDOM_ROOT_PASSWORD: 1
   wordpress:
     container_name: wordpress
     depends_on:
       - wordpress-db
     image: wordpress:latest
     ports:
       - 80:80
     restart: always
     volumes:
       - /srv/docker/wordpress/uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
       - /srv/docker/wordpress/html:/var/www/html
     environment:
       WORDPRESS_DB_HOST: wordpress-db:3306
       WORDPRESS_DB_USER: cloud1
       WORDPRESS_DB_PASSWORD: cloud1
       WORDPRESS_DB_NAME: wordpress
     
   wordpress-pma:
    image: phpmyadmin/phpmyadmin
    container_name: wordpress-pma
    depends_on:
        - wordpress-db
    environment:
        - PMA_HOST=wordpress-db
        - PMA_PORT=3306
        - PMA_ARBITRARY=1
    ports:
        - 8000:80
    restart: always